### PR TITLE
Refactor:

### PR DESCRIPTION
**Pull request by lenfree**
* Enable TCP check that doesn't return banner.
* Remove "return" keyword in method. In ruby, the value of the
  last line will be the method's return value.

### CODE REVIEW

**Comment by lenfree** [comment]
@mattyjones  I don't have to run the rake build, release. right? That should be executed by the build? :)

**Comment by mattyjones** [comment]
@lenfree  you run nothing ;)  Travis will handle everything.  You can test rubocop locally with `rubocop` or `rubocop -a` from the commandline

**Comment by lenfree** [comment]
@mattyjones  yep, I did the run rubocop. :) Wondering if how would you write a test for check-banner? hmm...

**Comment by mattyjones** [comment]
Tests are not required, just VERY strongly encouraged.  If you don't have tests it is not a deal breaker.  In this case you would run your tests with two sets of input, a banner and not banner. 

**Test 1** (input == banner)

* It should see the banner and exit ok
* It should see the banner and not exit with a non-ok

**Test 2** (input == '')

* It should not see the banner exit ok
* It should not see the banner and not exit with a non-ok

**Pull request merged**
