### PR TITLE
Add check-whois.rb

### PR DESCRIPTION
**Pull request by mijit**

### CODE REVIEW

**Comment by rmc3** [comment]
@mijit Sorry for the delay in looking at this. Would it be possible to change the name to something more descriptive? "check-whois" doesn't quite describe that it's a check which looks up expiry specifically, and there might be other checks in the future which look up other data with Whois. Perhaps "check-whois-expiry" or "check-whois-domain-expiry"?

**Comment by rmc3** [comment]
@mijit if you also wouldn't mind, Rubocop is a bit unhappy with your check because you don't have a documentation comment before the start of the class. Please add that , at minimum just the name of the class before the ```class``` line. Thanks!

**Comment by mijit** [comment]
Done! I'll remove this check from sensu-community-plugins once it's merged here.

**Comment by rmc3** [comment]
Thanks for the contribution, @mijit !

**Pull request merged**
