### PR TITLE
Add option to exclude newline from write string

### PR DESCRIPTION
**Pull request by dcharleston**

### CODE REVIEW

**Comment by eheydrick** [comment]
Is this backwards compatible? Wondering if it should include a newline only when an option is set.

**Comment by eheydrick** [comment]
Actually now I see it was previously doing a `puts` which would include a newline. Looks good to me. Can you add an entry to the CHANGELOG under unreleased and we'll get this merged.

**Comment by dcharleston** [comment]
@eheydrick CHANGELOG updated

**Comment by eheydrick** [comment]
Thanks @dcharleston!

**Pull request merged**
