### PR TITLE
bug fix for warn and crit values

### PR DESCRIPTION
**Pull request by aww-yiss**
Fix for https://github.com/sensu-plugins/sensu-plugins-network-checks/issues/81

Corrects warning and critical logic for number of days until expiration

### CODE REVIEW

**Comment by csabo** [comment]
Looks good, nice catch!

**Comment by majormoses** [comment]
Thanks for your contribution to Sensu plugins! Without people like you submitting PRs we couldn't run the project. I will review it shortly.

**Comment by majormoses** [comment]
Did a bit of git archeology and bug was introduced here: https://github.com/sensu-plugins/sensu-plugins-network-checks/commit/8b06cdaaa1c6a77ad72e5c5995841b3c6e7d1f1e#diff-56550700c877f2a3e27b58702171f4fc and was released in `2.3.0`

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-network-checks/versions/3.2.1

**Pull request merged**
