### PR TITLE
refactored check-ports.rb to use socket, not nmap - renamed old check…

### PR DESCRIPTION
**Pull request by countryHick**
…-ports to check-ports-nmap.rb

### CODE REVIEW

**Comment by countryHick** [comment]
oops :(  gimme a sec :)

**Comment by tas50** [comment]
Looks good.  Can you update the readme to include the new check and also make a quick update to the changelog with what you added.

**Comment by countryHick** [comment]
@mattyjones is this OK now, or no?

**Comment by mattyjones** [comment]
@countryHick   his looks great!

Can you do a rebase and then ping me and I will merge/build.

Thanks for this!

**Comment by countryHick** [comment]
@mattyjones - PR updated/rebased.

**Comment by mattyjones** [comment]
@countryHick  Cool, I am not sure why this is not letting me auto-merge if you did a rebase.  I will look into it tonight or tomorrow unless you have thoughts?

**Comment by countryHick** [comment]
huh - something else must have updated...

**Comment by patrickrand** [comment]
Any update on the merge status of this commit?
Thanks!

**Comment by mattyjones** [comment]
@patrickrand  I will take and merge this by hand for ya.

**Comment by liamjbennett** [comment]
When can we expect this change to be released?

**Comment by mattyjones** [comment]
@liamjbennett  @countryHick  @patrickrand  [0.0.7](https://rubygems.org/gems/sensu-plugins-network-checks/versions/0.0.7)

**Pull request merged**
