### PR TITLE
Add whois-parser to check-whois-domain-expiration.rb

### PR DESCRIPTION
**Pull request by akatch**
## Pull Request Checklist

This pull request is in response to #59 

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass

#### Purpose
To add the new whois-parser gem for use with the whois domain expiration checks.

#### Known Compatibility Issues
N/A

### CODE REVIEW

**Comment by majormoses** [comment]
validated:
```
$ bundle exec ./bin/check-whois-domain-expiration.rb --domain google.com
WhoisDomainExpirationCheck OK: google.com expires on 09-13-2020 (1139 days away)
```

**Comment by majormoses** [comment]
@akatch we probably need to adjust other checks as well but I validated that the one works. I am hesitant with this change without more testing. If you can show me a simple gist with the various options I can merge it faster if not I will need to take some time to do that this week.

**Comment by akatch** [comment]
@majormoses thanks for the quick review, and I understand your hesitation. I would be glad to get a gist going for you this evening. Stay tuned...

**Comment by akatch** [comment]
[Here](https://gist.github.com/akatch/b336d90fdb857e0c5c70df6a2f78ca01) is a quick gist of a few test cases as promised. I did need to make a change to the multidomain check, but the JSONwhois check does not use the whois or whois-parser gems so no change was necessary.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-network-checks/versions/2.0.0

**Pull request merged**
